#!/bin/bash
# To be placed in /usr/local/bin

release_file=/etc/os-release

if grep -i "arch" $release_file
then
    # The host is based on Arch
    echo "Running the pacman version of the command..."
    sudo pacman -Syu
fi

if grep -i "ubuntu" $release_file || grep -i "debian" $release_file
then
    # The host is based on Debian or Ubuntu
    echo "Running the apt version of the command..."
    sudo apt update
    sudo apt upgrade
fi

if grep -i "fedora" $release_file
then
    # The host is based on Fedora
    echo "Running the dnf version of the command..."
    sudo dnf update
fi
